import { registerIcons } from '@fluentui/react';
import { AscendingIcon, Blocked2Icon, CancelIcon, CheckMarkIcon, ChevronDownIcon, ChevronDownSmallIcon, ChevronLeftIcon, ChevronRightIcon, ChevronUpSmallIcon, CircleAdditionIcon, CircleAdditionSolidIcon, CircleRingIcon, ClearIcon, ClipboardListIcon, CodeIcon, ColorSolidIcon, CompletedIcon, CopyIcon, DatabaseIcon, DataManagementSettingsIcon, DeleteIcon, DescendingIcon, DoubleChevronDownIcon, DoubleChevronUpIcon, EditIcon, EmbedIcon, Emoji2Icon, ErrorBadgeIcon, FilterIcon, FilterSolidIcon, FunnelChartIcon, GroupListIcon, HideIcon, HomeIcon, InfoIcon, InstallationIcon, LocaleLanguageIcon, LocationIcon, MapLayersIcon, MoreIcon, MoreVerticalIcon, PermissionsIcon, PlugConnectedIcon, PlugDisconnectedIcon, ProductListIcon, PublishContentIcon, QueryListIcon, RedEyeIcon, RefreshIcon, RemoveFromShoppingListIcon, RevToggleKeyIcon, SadIcon, SaveIcon, SearchDataIcon, SearchIcon, ServerProcessesIcon, SettingsIcon, SkypeCheckIcon, StatusCircleCheckmarkIcon, StatusCircleErrorXIcon, StatusErrorFullIcon, SyncIcon, UploadIcon, ViewIcon } from '@fluentui/react-icons-mdl2';

// icons
registerIcons({
  icons: {
    circleAdditionSolid: <CircleAdditionSolidIcon />,
    circleAddition: <CircleAdditionIcon />,
    publishcontent: <PublishContentIcon />,
    installation: <InstallationIcon />,
    chevrondown: <ChevronDownIcon />,
    chevronright: <ChevronRightIcon />,
    mapLayers: <MapLayersIcon />,
    database: <DatabaseIcon />,
    permissions: <PermissionsIcon />,
    moreVertical: <MoreVerticalIcon />,
    clipboardList: <ClipboardListIcon />,
    embed: <EmbedIcon />,
    refresh: <RefreshIcon />,
    copy: <CopyIcon />,
    edit: <EditIcon />,
    plugDisconnected: <PlugDisconnectedIcon />,
    plugConnected: <PlugConnectedIcon />,
    filter: <FilterIcon />,
    filterSolid: <FilterSolidIcon />,
    funnelChart: <FunnelChartIcon />,
    more: <MoreIcon />,
    statusErrorFull: <StatusErrorFullIcon />,
    statusCircleErrorX: <StatusCircleErrorXIcon />,
    cancel: <CancelIcon />,
    chevrondownsmall: <ChevronDownSmallIcon />,
    chevronupsmall: <ChevronUpSmallIcon />,
    chevronleft: <ChevronLeftIcon />,
    redeye: <RedEyeIcon />,
    hide: <HideIcon />,
    doublechevrondown: <DoubleChevronDownIcon />,
    doublechevronup: <DoubleChevronUpIcon />,
    blocked2: <Blocked2Icon />,
    errorbadge: <ErrorBadgeIcon />,
    clear: <ClearIcon />,
    completed: <CompletedIcon />,
    delete: <DeleteIcon />,
    removeFromShoppingList: <RemoveFromShoppingListIcon />,
    skypeCircleCheck: <SkypeCheckIcon />,
    save: <SaveIcon />,
    revToggleKey: <RevToggleKeyIcon />,
    statuscirclecheckmark: <StatusCircleCheckmarkIcon />,
    circlering: <CircleRingIcon />,
    checkmark: <CheckMarkIcon />,
    grouplist: <GroupListIcon />,
    querylist: <QueryListIcon />,
    ascending: <AscendingIcon />,
    descending: <DescendingIcon />,
    view: <ViewIcon />,
    settings: <SettingsIcon />,
    colorsolid: <ColorSolidIcon />,
    localeLanguage: <LocaleLanguageIcon />,
    home: <HomeIcon />,
    search: <SearchIcon />,
    searchdata: <SearchDataIcon />,
    syncicon: <SyncIcon />,
    info: <InfoIcon />,
    ServerProcesses: <ServerProcessesIcon />,
    DataManagementSettings: <DataManagementSettingsIcon />,
    Code: <CodeIcon />,
    ProductList: <ProductListIcon />,
    Upload: <UploadIcon />,
    Sad: <SadIcon />,
    Emoji2: <Emoji2Icon />,
    Location: <LocationIcon />
  }
});