name: Release Server

# 新tag则release
on:
  push:
    tags:
      - 'v*server*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-frontend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out
      - uses: actions/checkout@v2
      # use node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          cd ./web
          npm install
          npm run build
      - name: Upload frontend build
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifact
          path: ./web/build
  
  goreleaser:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download frontend build
        uses: actions/download-artifact@v2
        with:
          name: frontend-artifact
          path: ./server/web/build

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      # - run: |
      #     go get -a

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: ./server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
